import fs from 'fs'
import path from 'path'

/** Traefik dynamic config: serve the copied-in certificate and send every HTTP request to HTTPS. */
export function tlsYaml(): string {
  return `# Generated by Purgatory at startup because certs/tls.crt and certs/tls.key exist.
# Remove the certificate files and restart Purgatory to go back to plain HTTP.
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/tls.crt
        keyFile: /certs/tls.key
http:
  routers:
    redirect-to-https:
      rule: "HostRegexp(\`.+\`)"
      priority: 10000
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: noop@internal
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
`
}

/** Both certificate files are present, i.e. HTTPS is (or will be, after sync) on. */
export function certsPresent(certDir = process.env.CERTS_DIR ?? '/app/certs'): boolean {
  return fs.existsSync(`${certDir}/tls.crt`) && fs.existsSync(`${certDir}/tls.key`)
}

/** HTTPS on iff both certificate files exist; returns the resulting mode. */
export function syncTlsConfig(
  certDir = process.env.CERTS_DIR ?? '/app/certs',
  dynamicDir = process.env.TRAEFIK_DYNAMIC_DIR ?? '/app/traefik-dynamic'
): 'enabled' | 'disabled' {
  const target = path.join(dynamicDir, 'tls.yml')
  if (certsPresent(certDir)) {
    const content = tlsYaml()
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) fs.writeFileSync(target, content)
    return 'enabled'
  }
  if (fs.existsSync(target)) fs.rmSync(target)
  return 'disabled'
}
